[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
secret_santa_lib = { path = "../secret_santa_lib" }
axum = {workspace = true}
tokio = {workspace = true}
serde = {workspace = true}
serde_json = {workspace = true}
